global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'statsd'
    static_configs:
      - targets: ['statsd-exporter:9102']
    
  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-webserver:8080']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432', 'postgres-etl:5432', 'postgres-prod:5432']